version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: food_delivery
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - food-delivery-network

  # User Service
  user-service:
    build: ./user-service
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/food_delivery
      SERVICE_NAME: user-service
    depends_on:
      - postgres
    networks:
      - food-delivery-network

  # Restaurant Service
  restaurant-service:
    build: ./restaurant-service
    ports:
      - "8002:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/food_delivery
      SERVICE_NAME: restaurant-service
    depends_on:
      - postgres
    networks:
      - food-delivery-network

  # Delivery Agent Service
  delivery-agent-service:
    build: ./delivery-agent-service
    ports:
      - "8003:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/food_delivery
      SERVICE_NAME: delivery-agent-service
    depends_on:
      - postgres
    networks:
      - food-delivery-network

volumes:
  postgres_data:

networks:
  food-delivery-network:
    driver: bridge
